### ISSUE TITLE
[charter] Define or remove "digital twins"

### ISSUE THREAD

**Issue by jyasskin** [w3c/smartcities-workshop#17]
The closest thing to a definition for "digital twins" in the charter is "Note that there are various definitions for "Digital Twins" like the following, so we’ll work on the common definition for “Digital Twins” as well.", but there's no "following" definition. If it appears in the name of the group, the charter should give a definition.

Or, it doesn't look like the term is actually used in the scope of the group, so maybe the group should just be named the "Smart Cities Interest Group".

**Comment by ashimura** [comment]
Terribly sorry it took very long to update the draft Charter, @jyasskin 

I've updated the [draft Charter](https://w3c.github.io/smartcities-workshop/draft-charter/index.html) based on your comment, and also some more comments I got offline.

The summary of updates is:
* Section "1.6 Digital Twins" as the Key Concept
  * added basic definition for "Digital Twins" at section based on the definition by ITU-T SG20 and ISO/IEC JTC1/WG11
  * added a figure about "Digital Twin Framework" right below the definition
  * moved the description about "a possible data connection mechanism for Web-based Digital Twins" from the Scope section to section 1.6
* Section "2. Scope"
  * added "Disaster countermeasure" to the list of possible topics
* Section "5.1 W3C Groups"
  * removed the categories of "Primary" and "Secondary"
  * removed Automotive WG, and added Automotive Ontology CG and Automotive Privacy Principles CG
* Section "5.2 External Organizations"
  * added brief description to the items that said "tbd"
  * added list of example countries and cities
 
Please see also the [detailed diff from the previous version](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fsmartcities-workshop%2Fmain%2Fdraft-charter%2Fbak.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fsmartcities-workshop%2Fmain%2Fdraft-charter%2Findex.html).

**Comment by jyasskin** [comment]
Thanks! I think that definition is sufficient to resolve this issue.

**Comment by ashimura** [comment]
Thank YOU, @jyasskin !
